"""
SOAP note model for clinical documentation.

Generated by ScribeAgent, reviewed/edited by physician.
Contains PHI - must be encrypted and audited.
"""

from typing import TYPE_CHECKING, Optional

from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Relationship, relationship

from .base import BaseModel

if TYPE_CHECKING:
    from .encounter import Encounter
    from .user import User


class SOAPNote(BaseModel):
    """
    SOAP (Subjective, Objective, Assessment, Plan) note.

    Generated by ScribeAgent, reviewed/edited by physician.
    Contains PHI - must be encrypted and audited.

    Attributes:
        encounter_id: Associated encounter
        subjective: Subjective section (patient's complaint)
        objective: Objective section (vitals, exam findings)
        assessment: Assessment section (diagnoses)
        plan: Plan section (treatment, follow-up)
        full_note: Complete SOAP note text
        generated_by_model: Claude model used for generation
        token_count: Total tokens used
        reasoning_trail: AI reasoning explanation
        was_edited: Whether physician edited note
        edit_count: Number of edits made
        reviewed_by: Physician who reviewed/approved
        is_signed: Whether note has been signed
        physician_rating: Quality rating (1-5)
    """

    __tablename__ = "soap_notes"

    # Foreign keys
    encounter_id = Column(
        Integer,
        ForeignKey("encounters.id"),
        nullable=False,
        unique=True,  # One note per encounter
        index=True,
        comment="Associated encounter",
    )

    # SOAP sections (all encrypted PHI)
    subjective = Column(
        Text,
        nullable=False,
        comment="Subjective section (patient's complaint)",
    )

    objective = Column(
        Text,
        nullable=False,
        comment="Objective section (vitals, exam findings)",
    )

    assessment = Column(
        Text,
        nullable=False,
        comment="Assessment section (diagnoses)",
    )

    plan = Column(
        Text,
        nullable=False,
        comment="Plan section (treatment, follow-up)",
    )

    # Full note (combined)
    full_note = Column(
        Text,
        nullable=False,
        comment="Complete SOAP note text",
    )

    # AI generation metadata
    generated_by_model = Column(
        String(100),
        nullable=False,
        comment="Claude model used (e.g., claude-sonnet-4-20250514)",
    )

    token_count = Column(
        Integer,
        nullable=False,
        comment="Total tokens used in generation",
    )

    reasoning_trail = Column(
        Text,
        nullable=True,
        comment="AI reasoning explanation",
    )

    # Physician review
    was_edited = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether physician edited AI-generated note",
    )

    edit_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of edits made",
    )

    reviewed_by = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=True,
        comment="Physician who reviewed/approved",
    )

    is_signed = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether note has been signed by physician",
    )

    # Quality metrics
    physician_rating = Column(
        Integer,
        nullable=True,
        comment="Physician quality rating (1-5 stars)",
    )

    # Relationships
    encounter: Relationship["Encounter"] = relationship(
        "Encounter",
        back_populates="soap_note",
    )

    reviewer: Relationship[Optional["User"]] = relationship(
        "User",
        foreign_keys=[reviewed_by],
    )

    def __repr__(self) -> str:
        """Return string representation."""
        return (
            f"<SOAPNote(id={self.id}, encounter_id={self.encounter_id}, "
            f"signed={self.is_signed})>"
        )

    def mark_edited(self) -> None:
        """Mark note as edited by physician."""
        self.was_edited = True
        self.edit_count += 1

    def sign(self, reviewer_id: int) -> None:
        """Sign the SOAP note.

        Args:
            reviewer_id: ID of physician signing the note
        """
        self.reviewed_by = reviewer_id
        self.is_signed = True

    def rate(self, rating: int) -> None:
        """Rate the AI-generated note quality.

        Args:
            rating: Quality rating from 1-5

        Raises:
            ValueError: If rating not in valid range
        """
        if not 1 <= rating <= 5:
            raise ValueError("Rating must be between 1 and 5")
        self.physician_rating = rating

    def get_sections(self) -> dict:
        """Get SOAP sections as dictionary.

        Returns:
            Dictionary with S, O, A, P sections
        """
        return {
            "subjective": self.subjective,
            "objective": self.objective,
            "assessment": self.assessment,
            "plan": self.plan,
        }
